apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
        - name: shipping
          image: grpc-shipping:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: ENV
              value: "production"
            - name: DATA_SOURCE_URL
              value: "root:minhasenha@tcp(mysql:3306)/shipping?charset=utf8mb4&parseTime=True&loc=Local"
            - name: APPLICATION_PORT
              value: "3002"
          ports:
            - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: default
spec:
  selector:
    app: shipping
  ports:
    - port: 3002
      targetPort: 3002
